# -*- coding: utf-8 -*-
"""bots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150jmzyNn8t6JO4xvjJNZB79TqhtsVitE
"""

# MINI_GEMINI BOT

!pip install pyTelegramBotAPI
!pip install openai
!pip install google-generativeai #For Google Gemini #AIMERS
!pip install anthropic

#Latest version #Gemini API
import telebot
import os

import google.generativeai as genai

TelegramBOT_TOKEN = '7118016152:AAHDSr-6RLKHbNYM88SSpiYO_Cz6M73aHSA'
genai.configure(api_key="AIzaSyBpnyPGbm4oLA8Wk7GuFF0R8AwbzgKBJfY")

# Set up the model
generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 0,
  "max_output_tokens": 8192,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest",
                              generation_config=generation_config,
                              safety_settings=safety_settings)


import telebot
import os

import google.generativeai as genai

TelegramBOT_TOKEN = '7118016152:AAHDSr-6RLKHbNYM88SSpiYO_Cz6M73aHSA'
genai.configure(api_key="AIzaSyBpnyPGbm4oLA8Wk7GuFF0R8AwbzgKBJfY")

# Set up the model
generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 0,
  "max_output_tokens": 8192,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

convo = model.start_chat(history=[

])

bot = telebot.TeleBot(TelegramBOT_TOKEN)

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Welcome! The MOST POWERFUL GEMINI AI BOT by Naveen_bots")

@bot.message_handler(func=lambda message: True)
def handle_message(message):
 try :
  print(message)
  convo.send_message(message.text)
  bot.reply_to(message, convo.last.text)
 except Exception as e:
        print(f"An error occurred: {e}")
        bot.reply_to(message, "Sorry, I couldn't process your request.")
bot.polling()
